# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Derive the logarithm of the likelihood of a multivariate normal distribution
#' 
#' @param X Vector, a vector of numeric values
#' @param mean Vector, the mean of multivariate normal
#' @param Sigma Matrix, the variance-covariance matrix of multivariate normal 
#' @return Returns the logarithm of the likelihood of X with multivariate normal with mean \code{mean} and variance \code{Sigma}
#'
#' @keywords internal
#'
logdmvnorm <- function(X, mean, Sigma) {
    .Call(`_nonparlongdat_logdmvnorm`, X, mean, Sigma)
}

#' Identify subject index from the validation set
#' 
#' @param Xi Vector, a vector of numeric values
#' @param Xj Vector, a vector of numeric values
#' @return Returns a vector identifying valid \code{Xi} for \code{Xj}
#' 
#' @keywords internal
#'
ideniforj <- function(Xi, Xj) {
    .Call(`_nonparlongdat_ideniforj`, Xi, Xj)
}

#' Determine variance-covariance matrix (with correct dimension)
#' 
#' @param Xi Vector, a vector of numeric values
#' @param Sigma Matrix, a variance-covariance matrix
#' @return Returns a variance-covariance matrix of correct dimension based on the index of \code{Xi}
#' 
#' @keywords internal
#'
idensigmaforj <- function(Xi, Sigma) {
    .Call(`_nonparlongdat_idensigmaforj`, Xi, Sigma)
}

#' Calculate the log-likelhood of the validation set
#' 
#' @param Y Matrix, a matrix of outcomes
#' @param X Matrix, a matrix with missing covariates
#' @param Z Matrix, a matrix with fully-observed covariates
#' @param theta Vector, a vector of unknown parameters
#' @param Sigma Matrix, a matrix of variance-covariance structure
#' @return Returns the log-likelihood of the validation set
#' 
#' @keywords internal
#'
loglikvalid <- function(Y, X, Z, theta, Sigma) {
    .Call(`_nonparlongdat_loglikvalid`, Y, X, Z, theta, Sigma)
}

#' Calculate the log-likelihood of the non-validation set (time-invariant X and time-invariant auxiliary variables)
#' 
#' @param Yval Matrix, a matrix of outcomes from the validation set
#' @param Ynonval Matrix, a matrix of outcomes from the non-validation set
#' @param Xval Matrix, a matrix of missing covariates from the validation set
#' @param Xnonval Matrix, a matrix of missing covariates from the non-validation set
#' @param Z Matrix, a matrix with fully-observed covariates
#' @param auxval Matrix, a matrix of auxiliary variables from the validation set
#' @param auxnonval Matrix, a matrix of auxiliary variables from the non-validation set
#' @param theta Vector, a vector of unknown parameters
#' @param Sigma Matrix, a matrix of variance-covariance structure
#' @param H Vector, a vector of bandwidths
#' @param auxcont, a logistic argument determining whether the auxiliary variables are continuous
#' @return Returns the log-likelihood contributed by the non-validation set with time-invariant X and time-invariant auxliary variables
#' 
#' @keywords internal
#'
logliknonvalidXinvauxinv <- function(Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont) {
    .Call(`_nonparlongdat_logliknonvalidXinvauxinv`, Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont)
}

#' Calculate the log-likelihood of the non-validation set (time-varying X and time-invariant auxiliary variables)
#'
#' @param Yval Matrix, a matrix of outcomes from the validation set
#' @param Ynonval Matrix, a matrix of outcomes from the non-validation set
#' @param Xval Matrix, a matrix of missing covariates from the validation set
#' @param Xnonval Matrix, a matrix of missing covariates from the non-validation set
#' @param Z Matrix, a matrix with fully-observed covariates
#' @param auxval Matrix, a matrix of auxiliary variables from the validation set
#' @param auxnonval Matrix, a matrix of auxiliary variables from the non-validation set
#' @param theta Vector, a vector of unknown parameters
#' @param Sigma Matrix, a matrix of variance-covariance structure
#' @param H Vector, a vector of bandwidths
#' @return Returns the log-likelihood contributed by the non-validation set with time-varying X and time-invariant auxliary variables
#' 
#' @keywords internal
#'
logliknonvalidXvaryauxinv <- function(Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H) {
    .Call(`_nonparlongdat_logliknonvalidXvaryauxinv`, Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H)
}

#' Calculate the log-likelihood of the non-validation set (time-varying X and time-varying auxiliary variables)
#' 
#' @param Yval Matrix, a matrix of outcomes from the validation set
#' @param Ynonval Matrix, a matrix of outcomes from the non-validation set
#' @param Xval Matrix, a matrix of missing covariates from the validation set
#' @param Xnonval Matrix, a matrix of missing covariates from the non-validation set
#' @param Z Matrix, a matrix with fully-observed covariates
#' @param auxval Matrix, a matrix of auxiliary variables from the validation set
#' @param auxnonval Matrix, a matrix of auxiliary variables from the non-validation set
#' @param theta Vector, a vector of unknown parameters
#' @param Sigma Matrix, a matrix of variance-covariance structure
#' @param H Vector, a vector of bandwidths
#' @param auxcont, a logistic argument determining whether the auxiliary variables are continuous
#' @return Returns the log-likelihood contributed by the non-validation set with time-varying X and time-varying auxliary variables
#' 
#' @keywords internal
#'
logliknonvalidXvaryauxvary <- function(Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont) {
    .Call(`_nonparlongdat_logliknonvalidXvaryauxvary`, Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont)
}

