# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logdmvnorm <- function(X, mean, Sigma) {
    .Call('_nonparlongdat_logdmvnorm', PACKAGE = 'nonparlongdat', X, mean, Sigma)
}

ideniforj <- function(Xi, Xj) {
    .Call('_nonparlongdat_ideniforj', PACKAGE = 'nonparlongdat', Xi, Xj)
}

idensigmaforj <- function(Xi, Sigma) {
    .Call('_nonparlongdat_idensigmaforj', PACKAGE = 'nonparlongdat', Xi, Sigma)
}

loglikvalid <- function(Y, X, Z, theta, Sigma) {
    .Call('_nonparlongdat_loglikvalid', PACKAGE = 'nonparlongdat', Y, X, Z, theta, Sigma)
}

logliknonvalidXinvauxinv <- function(Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont) {
    .Call('_nonparlongdat_logliknonvalidXinvauxinv', PACKAGE = 'nonparlongdat', Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont)
}

logliknonvalidXvaryauxinv <- function(Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H) {
    .Call('_nonparlongdat_logliknonvalidXvaryauxinv', PACKAGE = 'nonparlongdat', Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H)
}

logliknonvalidXvaryauxvary <- function(Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont) {
    .Call('_nonparlongdat_logliknonvalidXvaryauxvary', PACKAGE = 'nonparlongdat', Yval, Ynonval, Xval, Xnonval, Z, auxval, auxnonval, theta, Sigma, H, auxcont)
}

